<html>
<head>

</head>
<body>

<h1>Accuracy tests of JS code samples in notes below ...</h1>
<h2>
<script>
'use strict'










// function myFunction() {
//     let x = 9;
//     if (!x > 10) { // evaluates to true
//         document.write("true");
//     } else {
//         document.write("false");
//     }
    
// }
// myFunction(); // outputs true

// function myFunction() {
//     // let x = 10;
//     let result;

//     try {
//         result = x / 10; // an error occurs here        
//     }
//     catch (error) {
//         // throw new error object is generated here with two properties: name, message.
//         // let errorMessage = {
//         //     name: `Here's the name`,
//         //     content: `Who fucking knows?`,
//         // };
//         // throw new Error(errorMessage.name, errorMessage.content);
//         // document.write(`<br><strong>` + error.name + `:</strong> <em>` + error.message + `</em>`); // this line will run if there was an error in the try code block\
//         document.write(Error.prototype.name.toString());
//         document.write(Error.prototype.message.toString());
//     }
//     finally {}
// }
// myFunction();
function attemptDivision() {
    let result;

    try {
        result = x / 10;
    } catch (error) {
        throw {
            "message" : "In the attemptDivsion() method, the following error occurred: " + error.message,
            "name" : "CustomError",
        }
    }    
}
function throwError() {
    try {
        attemptDivision();
    } catch (error) {
        console.log(error.message + " - Error Type: " + error.name);
    }
}
throwError(); // the console shows the followiing ... "In the attemptDivsion() method, the following error occurred: x is not defined - Error Type: CustomError"














</script>
</h2>


</body>
</html>

